apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: alertmanager
type: Opaque
stringData:
  AUTH_PASSWORD: "{{your_email_app_password}}"
  SLACK_API_URL: "{{your_webhook_url}}"