apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
  labels:
    app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      
    scrape_configs:
      - job_name: 'darksignal-server'
        static_configs:
          - targets: ['darksignal-server.darksignal.svc.cluster.local:5080']

    rule_files:
      - /etc/prometheus/rules/rules.yaml

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager.alertmanager.svc.cluster.local:9093']
    
