apiVersion: v1
kind: Service
metadata:
  name: darksignal-server
  namespace: darksignal
spec:
  selector:
    app: darksignal-server
  ports:
    - protocol: TCP
      port: 5080
      targetPort: 5080
  type: NodePort
