name: SRE Project - Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGISTRY: docker.io
  WEB_APP_IMAGE_NAME: dantr3/sre-project
  SCRIPT_IMAGE_NAME: dantr3/sre-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build Web App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: | 
            ${{ env.REGISTRY }}/${{ env.WEB_APP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.WEB_APP_IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Build Script Image
        uses: docker/build-push-action@v5
        with:
          context: ./scripts
          file: ./scripts/dockerfile 
          push: ${{ github.event_name == 'push' }}
          tags: | 
            ${{ env.REGISTRY }}/${{ env.SCRIPT_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.SCRIPT_IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0  
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform/eks
        run: |
          terraform init \
            -backend-config="bucket=sre-project-s3-dantr3-bucket" \
            -backend-config="key=sre-project/eks/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Plan
        working-directory: ./terraform/eks
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform/eks
        run: terraform apply -auto-approve tfplan

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Show Terraform Outputs
        working-directory: ./terraform/eks
        run: |
          echo "==== Terraform Outputs ===="
          terraform output
          echo "=========================="

      - name: Capture Terraform Outputs
        run: |
          REGION=$(terraform output -raw region)
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $REGION --name $CLUSTER_NAME
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f infra/namespaces/
          kubectl apply -f infra/alertmanager/
          kubectl apply -f infra/prometheus/
          kubectl apply -f infra/grafana/
          kubectl apply -f infra/web_app/
          kubectl apply -f infra/script/

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/darksignal-server -n darksignal --timeout=5m

      - name: Post deployment info
        run: |
          echo "âœ… Deployment successful!"
          kubectl get pods -A
          kubectl get services -A
