name: SRE Project - Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGISTRY: docker.io
  WEB_APP_IMAGE_NAME: dantr3/sre-project
  SCRIPT_IMAGE_NAME: dantr3/sre-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Web App Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.WEB_APP_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.WEB_APP_IMAGE_NAME }}:${{ github.sha.substr(0, 8) }}

      - name: Build Script Image
        uses: docker/build-push-action@v5
        with:
          context: ./scripts
          file: ./scripts/dockerfile 
          push: ${{ github.event_name == 'push' }}
          tags: | 
            ${{ env.REGISTRY }}/${{ env.SCRIPT_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.SCRIPT_IMAGE_NAME }}:${{ github.sha.substr(0, 8) }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      
      #THIS IS WHERE YOU CONNECT TO YOUR CLUSTER (AZURE, AWS, GCP... ETC)
      #- name: Configure kubeconfig
      #  run: |
      #    mkdir -p $HOME/.kube
      #    echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      #   chmod 600 $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          # Create namespaces first
          kubectl apply -f infra/namespaces/
          
          # Apply all configurations and deployments
          kubectl apply -f infra/alertmanager/
          kubectl apply -f infra/prometheus/
          kubectl apply -f infra/grafana/
          kubectl apply -f infra/web_app/
          kubectl apply -f infra/script/

      - name: Verify deployment
        run: |
          kubectl rollout status darksignal-server -n darksignal --timeout=5m

      - name: Post deployment info
        if: success()
        run: |
          echo "âœ… Deployment successful!"
          kubectl get pods -A
          kubectl get services -A
